### ISSUE TITLE
Saving test arguments via Dashboard not possible

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#2789]
**Describe the bug**
It is not possible to set 

**To Reproduce**
1. Create a test
2. Open dashboard
3. Click on test
4. Click on Settings -> Variables & Secrets
5. Enter text in Arguments textbox
6. "Save" button is greyed out and not clickable

**Expected behavior**
Arguments can be saved and are added to next test run

**Version / Cluster**
- Which testkube version? 1.7.10 Client + Server

**Screenshots**
![Bildschirmfoto 2022-11-23 um 16 27 11](https://user-images.githubusercontent.com/54187283/203594935-64d76199-3618-41b1-be7e-d887f99ba405.png)

**Comment by scott-david-walker** [comment]
It's worthwhile to add that this is also the case for the environment variables. They are always greyed out

**Comment by f-helm** [comment]
Seems like this is fixed in version 1.7.17?

**Comment by pavloburchak** [comment]
@f-helm yes, it is

**Comment by scott-david-walker** [comment]
I'm still having the issue. Using a helm install version 1.7.72. All arguments default
