### ISSUE TITLE
testkube 1.9.{30,31} completion generation issue

### ISSUE THREAD

**Issue by chenrui333** [kubeshop/testkube#3392]
While trying to upgrade the build, but found some completion generation issue as below:

```
panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x2 addr=0x1d0 pc=0x1018802e8]
  
  goroutine 1 [running]:
  github.com/kubeshop/testkube/pkg/k8sclient.GetK8sClientConfig()
  	github.com/kubeshop/testkube/pkg/k8sclient/k8sclient.go:75 +0x88
  github.com/kubeshop/testkube/pkg/k8sclient.ConnectToK8s()
  	github.com/kubeshop/testkube/pkg/k8sclient/k8sclient.go:30 +0x1c
  github.com/kubeshop/testkube/pkg/telemetry.GetClusterType()
  	github.com/kubeshop/testkube/pkg/telemetry/telemetry.go:110 +0x24
  github.com/kubeshop/testkube/pkg/telemetry.SendCmdEvent(0x1?, {0x101c6a1d4, 0x6})
  	github.com/kubeshop/testkube/pkg/telemetry/telemetry.go:44 +0xd0
  github.com/kubeshop/testkube/cmd/kubectl-testkube/commands.glob..func2(0x14000a3cc00?, {0x102ff3[158](https://github.com/Homebrew/homebrew-core/actions/runs/4381369413/jobs/7669429401#step:7:159)?, 0x0?, 0x0?})
  	github.com/kubeshop/testkube/cmd/kubectl-testkube/commands/root.go:69 +0xd4
  github.com/spf13/cobra.(*Command).execute(0x14000a3cc00, {0x102ff3158, 0x0, 0x0})
  	github.com/spf13/cobra@v1.6.1/command.go:936 +0x6ec
  github.com/spf13/cobra.(*Command).ExecuteC(0x102f89760)
  	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
  github.com/spf13/cobra.(*Command).Execute(...)
  	github.com/spf13/cobra@v1.6.1/command.go:968
  github.com/kubeshop/testkube/cmd/kubectl-testkube/commands.Execute()
  	github.com/kubeshop/testkube/cmd/kubectl-testkube/commands/root.go:126 +0x2dc
  main.main()
  	./main.go:24 +0x1c
  Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /opt/homebrew/Cellar/testkube/1.9.30/bin/kubectl-testkube completion bash` exited with 2. Here's the output:

```

relates to https://github.com/Homebrew/homebrew-core/pull/125279
full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4381369413/jobs/7669429401

**Comment by vsukhin** [comment]
fixed in https://github.com/kubeshop/testkube/commit/92206d806427ef936ac7899e120208078e033870

**Comment by chenrui333** [comment]
Thanks!

**Comment by chenrui333** [comment]
@vsukhin actually this is still happening, see https://github.com/Homebrew/homebrew-core/pull/125756

**Comment by vsukhin** [comment]
official homebrew is lagging a lot, you can fine latest testkube in our repo https://github.com/kubeshop/homebrew-testkube

**Comment by chenrui333** [comment]
np

**Comment by vsukhin** [comment]
should be fixed soon. thank you for noting!

**Comment by chenrui333** [comment]
Trying in https://github.com/Homebrew/homebrew-core/pull/125859, thanks!
